### ISSUE TITLE
ERROR [FakePlayerManager] 连接WebSocket时发生错误，错误代码: 0

### ISSUE THREAD

**Issue by XCLHove** [LiteLScript-Dev/FakePlayerManager#1]
ERROR [FakePlayerManager] 连接WebSocket时发生错误，错误代码: 0

**Comment by xiaoqch** [comment]
错误代码0应该是无法连接到ws服务器，请确保
1.已安装假人客户端并启用ws服务器，如图
![image](https://user-images.githubusercontent.com/37901097/158044920-0fc14431-69c6-426a-8049-61788f2d9652.png)

2.假人管理插件配置的ws服务端端口与假人客户端端口一致，如图
![image](https://user-images.githubusercontent.com/37901097/158044945-6b86ff51-ed45-4b84-91e9-2221bbdbc6be.png)

**Comment by XCLHove** [comment]
发现问题所在了，我用的linux，然后在docker中运行的bds，而fakePlayer是在linux中运行，不在同一内网，无法回环连接

**Comment by xiaoqch** [comment]
与假人管理插件无关，关闭此issue
